<?php
  $json = file_get_contents("https://covid19.ddc.moph.go.th/api/Cases/today-cases-by-provinces");
  $data = json_decode($json);

  echo "<table border='1'>";
  echo"<caption>";
  echo "<h3>";
  echo "<p>";
  echo "รายงานสถานการโควิด-19 แยกจังหวัด";
  echo "</p>";
  echo "</h3>";
  echo"</caption>";
  echo "<tr align = 'center'>";
  echo "<td bgcolor='#CCFFFF'>"; 
  echo "ลำดับ";
  echo "</td>"; 
  echo "<td bgcolor='#CCFFCC'>"; 
  echo "จังหวัด";
  echo "</td>";
  echo "<td bgcolor='#CCFF99'>"; 
  echo "ผู้ป่วยใหม่";
  echo "</td>"; 
  echo "<td bgcolor='#CCFF66'>"; 
  echo "ผู้ป่วยรวม";
  echo "</td>"; 
  echo "<td bgcolor='#CCFF33'>"; 
  echo "ผู้ป่วยใหม่ในประเทศ";
  echo "</td>"; 
  echo "<td bgcolor='#CCFF00'>"; 
  echo "ผู้ป่วยรวมในประเทศ";
  echo "</td>"; 
  echo "<td bgcolor='#CCCC33'>"; 
  echo "ผู้เสียชีวิตใหม่";
  echo "</td>"; 
  echo "<td bgcolor='#CCCC00'>"; 
  echo "ผู้เสียชีวิตรวม";
  echo "</td>";
  echo "<td bgcolor='#20B2AA'>"; 
  echo "วันที่อัพเดท";
  echo "</td>";  
  echo "</tr>";

  foreach($data as $key=>$val){
    echo "<tr align = 'center'>";
    echo "<tr align = 'center'>";
    echo "<td bgcolor='#CCFFFF'>"; 
    echo $key+1;
    echo "</td>"; 
    echo "<td bgcolor='#CCFFCC'>"; 
    echo $val->province;
    echo "</td>";
    echo "<td bgcolor='#CCFF99'>"; 
    echo $val->new_case;
    echo "</td>";
    echo "<td bgcolor='#CCFF66'>"; 
    echo $val->total_case;
    echo "</td>";
    echo "<td bgcolor='#CCFF33'>"; 
    echo $val->new_case_excludeabroad;
    echo "</td>";
    echo "<td bgcolor='#CCFF00'>"; 
    echo $val->total_case_excludeabroad;
    echo "</td>";
    echo "<td bgcolor='#CCCC33'>"; 
    echo $val->new_death;
    echo "</td>";
    echo "<td bgcolor='#CCCC00'>"; 
    echo $val->total_death;
    echo "</td>"; 
    echo "<td bgcolor='#E0FFFF'>"; 
    echo $val->update_date;
    echo "</td>";
    echo "</tr>";

  }
  echo "</table>";
